// Generated by gencpp from file aubo_planning/grasp_poseResponse.msg
// DO NOT EDIT!


#ifndef AUBO_PLANNING_MESSAGE_GRASP_POSERESPONSE_H
#define AUBO_PLANNING_MESSAGE_GRASP_POSERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aubo_planning
{
template <class ContainerAllocator>
struct grasp_poseResponse_
{
  typedef grasp_poseResponse_<ContainerAllocator> Type;

  grasp_poseResponse_()
    : success(false)  {
    }
  grasp_poseResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::aubo_planning::grasp_poseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aubo_planning::grasp_poseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct grasp_poseResponse_

typedef ::aubo_planning::grasp_poseResponse_<std::allocator<void> > grasp_poseResponse;

typedef boost::shared_ptr< ::aubo_planning::grasp_poseResponse > grasp_poseResponsePtr;
typedef boost::shared_ptr< ::aubo_planning::grasp_poseResponse const> grasp_poseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aubo_planning::grasp_poseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aubo_planning::grasp_poseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::aubo_planning::grasp_poseResponse_<ContainerAllocator1> & lhs, const ::aubo_planning::grasp_poseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::aubo_planning::grasp_poseResponse_<ContainerAllocator1> & lhs, const ::aubo_planning::grasp_poseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace aubo_planning

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::aubo_planning::grasp_poseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aubo_planning::grasp_poseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aubo_planning::grasp_poseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aubo_planning::grasp_poseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aubo_planning::grasp_poseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aubo_planning::grasp_poseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aubo_planning::grasp_poseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::aubo_planning::grasp_poseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::aubo_planning::grasp_poseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aubo_planning/grasp_poseResponse";
  }

  static const char* value(const ::aubo_planning::grasp_poseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aubo_planning::grasp_poseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
"\n"
;
  }

  static const char* value(const ::aubo_planning::grasp_poseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aubo_planning::grasp_poseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct grasp_poseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aubo_planning::grasp_poseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aubo_planning::grasp_poseResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUBO_PLANNING_MESSAGE_GRASP_POSERESPONSE_H
